### ISSUE TITLE
New Inspection Forms

### ISSUE THREAD

**Issue by tvbarnette999** [tvbarnette999/nc-ftc-inspection#5]
With the possibility of the double columned inspection form, we will at some point need to redo the way we save and display inspection forms. Currently, its a Vector of Strings, and the file is just those strings on separate lines. The booleans for the checkboxes are indexed to this vector. I'm thinking that we will need to move to a OO format for the forms. Since the indexing the Checkboxes makes the JS really easy, we should keep that, and have the Form class generate the HTML so the indexing is correct. My thoughts are a Vector of <FormElement>, which model each row of the form. FormSectionHead and FormRow are the children of abstract FormElement. SectionHead has no checkboxes, but Column titles, while FormRows have # of checkboxes, string, and rules. One Immediate Problem is the NAs in the DS column. What thoughts do you have on the matter?

**Comment by adwiii** [comment]
Alternatively, if you didn't want to redo the structure we had, you could
have a String flag that's just an end of line char, etc. and store all of
the first column in the vector before that and all of the second column
after. That'd also be expandable to more columns if the need arises, and we
don't have to change much.
